import {
  RememberMe as RememberMeIcon,
  Diversity3 as Diversity3Icon,
  Home as HomeIcon,
  Layers as LayersIcon,
  Book as BookIcon,
  Kitchen as KitchenIcon,
  People as PeopleIcon,
  PlayCircle as PlayCircleIcon,
  Bookmarks as BookmarksIcon,
  BookmarkAdd as BookmarkAddIcon,
  Info as InfoIcon,
  Star as StarIcon,
  AlternateEmail as AlternateEmailIcon,
  House as HouseIcon,
  LastPage as LastPageIcon,
  Bookmark as BookmarkIcon,
  EditNote as EditNoteIcon,
  Textsms as TextsmsIcon,
  MarkUnreadChatAlt as MarkUnreadChatAltIcon,
  QuestionAnswer as QuestionAnswerIcon,
  Settings as SettingsIcon,
  Terminal as TerminalIcon,
  TaxiAlert as TaxiAlertIcon,
  AdminPanelSettings as AdminPanelSettingsIcon,
  DinnerDining as DinnerDiningIcon,
  Favorite as FavoriteIcon,
} from '@mui/icons-material'
export const links = [
  { name: 'Receitas', icon: <StarIcon />, link: '/topReview' },
  {
    name: 'Minhas Receitas',
    icon: <BookIcon />,
    link: '/my-recipes',
  },
  {
    name: 'Receitas Favoritas',
    icon: <FavoriteIcon />,
    link: '/youfavoriteRecipes',
  },

  {
    name: 'Nova Receita',
    icon: <BookmarkAddIcon />,
    link: '/createRecipes',
  },
  { name: 'Gerador de receitas', icon: <DinnerDiningIcon /> },
  {
    name: 'Comunidade',
    icon: <Diversity3Icon />,
    link: '/comunidade',
  },
]
